include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/**.gr.dart
    - lib/**.g.dart
    - lib/**.freezed.dart

linter:
  rules:
    sort_constructors_first: true
    always_use_package_imports: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    public_member_api_docs: false
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    annotate_overrides: true
    escape_catching_errors: true
    avoid_init_to_null: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_private_typedef_functions: true
    avoid_types_on_closure_parameters: true
    avoid_types_as_parameter_names: true
    empty_statements: true
    constant_identifier_names: true
    directives_ordering: true
    empty_constructor_bodies: true
    file_names: true
    list_remove_unrelated_type: true
    valid_regexps: true
    prefer_void_to_null: true
    no_logic_in_create_state: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    overridden_fields: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_null_aware_operators: true
    sort_child_properties_last: true
    type_annotate_public_apis: false
    unnecessary_null_in_if_null_operators: true
    prefer_single_quotes: true
    use_build_context_synchronously: true
    use_super_parameters: true
    always_put_required_named_parameters_first: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 55
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
